#define AppVersion "0.5.0"
#define AppName "MyFile Converter"
#define AppPublisher "MyFile Converter"
#define AppExeName "MyFileConverter.exe"
#define AppSetupBaseName "MyFileConverter_Setup_0.5.0_x64"
